name: Deploy React App to Firebase

on:
  push:
    branches:
      - main   # Run only when pushing to main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js (use exact version your app needs)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build the React project
      - name: Build app
        run: npm run build

      # 5️⃣ Deploy to Firebase Hosting (OFFICIAL ACTION)
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}" # Its fetched automatically from github
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: netflix-gpt-bcf8a
